language: java
sudo: true
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
matrix:
  include:
    - jdk: oraclejdk8
      env: TEST="test.HardHandTest"
    - jdk: oraclejdk8
      env: TEST="test.SoftHandTest"
script: ./gradlew test -i --tests $TEST