language: java
sudo: true
before_install:
- chmod +x gradlew
matrix:
  include:
    - jdk: oraclejdk8
      env: TEST="test.HardHandTest"
    - jdk: oraclejdk8
      env: TEST="test.SoftHandTest"
    - jdk: oraclejdk8
      env: TEST="test.SurrenderTest"
    - jdk: oraclejdk8
      env: TEST="test.H16vTNSTest"
    - jdk: oraclejdk8
      env: TEST="test.SplittingEights"
script: ./gradlew test -i --tests $TEST